In [4]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 
import seaborn as sns

LOADING OF DATASET OF 100MB

In [5]:
df = pd.read_csv('student_mental_health_burnout_1M.csv')
df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,4.404825,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,2.664749,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,4.219224,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,3.634823,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,5.501813,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000

STARTING 5 ROWS

In [6]:
df.head()

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000

ENDING 5 ROWS

In [7]:
df.tail()

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,4.404825,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,2.664749,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,4.219224,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,3.634823,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,5.501813,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000

AN OVERVIEW OF DATASET -->  Column,Non-Null, Count, Dtype

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   age                   1000000 non-null  int64
 1   gender                1000000 non-null  object
 2   academic_year         1000000 non-null  int64
 3   study_hours_per_day   1000000 non-null  float64
 4   exam_pressure         1000000 non-null  float64
 5   academic_performance  1000000 non-null  float64
 6   stress_level          1000000 non-null  float64
 7   anxiety_score         1000000 non-null  float64
 8   depression_score      1000000 non-null  float64
 9   sleep_hours           1000000 non-null  float64
 10  physical_activity     1000000 non-null  float64
 11  social_support        1000000 non-null  float64
 12  screen_time           1000000 non-null  float64
 13  internet_usage        1000000 non-null  float64
 14  financial_stress      1000000 non-null  float64
 15  family_expectation    1000000 non-null  float64
 16  burnout_score         1000000 non-null  float64
 17  mental_health_index   1000000 non-null  float64
 18  risk_level            1000000 non-null  object
 19  dropout_risk          1000000 non-null  float64
dtypes: float64(16), int64(2), object(2)
memory usage: 152.6+ MB

CHECKING THE NULL VALUES

In [9]:
df.isna().sum() # there is no null values in the data

age                     0
gender                  0
academic_year           0
study_hours_per_day     0
exam_pressure           0
academic_performance    0
stress_level            0
anxiety_score           0
depression_score        0
sleep_hours             0
physical_activity       0
social_support          0
screen_time             0
internet_usage          0
financial_stress        0
family_expectation      0
burnout_score           0
mental_health_index     0
risk_level              0
dropout_risk            0
dtype: int64

A SUMMARY OF STATISTICS

In [10]:
df.describe()

,age,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,dropout_risk
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,22.996456,2.500782,5.001727,5.998810,70.999135,4.246462,2.986413,1.274728,6.501713,3.011153,4.999724,5.018766,5.038116,5.002920,5.983287,1.784073,7.023073,1.324896
std,3.742579,1.117749,1.989340,1.548268,5.660073,1.678998,1.509844,1.221273,1.472972,1.463679,1.976536,1.960599,2.157838,1.976426,1.960972,1.664035,1.310698,1.342727
min,17.000000,1.000000,0.000000,1.000000,42.365714,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.309745,0.000000
25%,20.000000,2.000000,3.650644,4.944647,67.180912,3.102593,1.923747,0.005198,5.491047,1.990596,3.650029,3.651138,3.491114,3.656767,4.647065,0.124810,6.141553,0.000000
50%,23.000000,3.000000,4.998222,5.998906,70.999914,4.244029,2.969514,1.047839,6.501938,3.000619,4.999017,5.003518,5.001542,5.001279,5.999517,1.496505,7.074414,1.009531
75%,26.000000,4.000000,6.345532,7.051914,74.820937,5.385464,4.014996,2.086397,7.514642,4.011208,6.349751,6.351386,6.506834,6.354571,7.351578,2.889473,7.962169,2.173661
max,29.000000,4.000000,14.000000,10.000000,97.246309,10.000000,10.000000,8.530800,10.000000,7.000000,10.000000,12.000000,14.000000,10.000000,10.000000,10.000000,10.000000,9.326226

DATASET SHAPE

In [11]:
df.shape #gives you the shape of the dataframe in(row,coloumns)

(1000000, 20)

DATA COLUMNS DATATYPES

In [12]:
df.dtypes

age                       int64
gender                   object
academic_year             int64
study_hours_per_day     float64
exam_pressure           float64
academic_performance    float64
stress_level            float64
anxiety_score           float64
depression_score        float64
sleep_hours             float64
physical_activity       float64
social_support          float64
screen_time             float64
internet_usage          float64
financial_stress        float64
family_expectation      float64
burnout_score           float64
mental_health_index     float64
risk_level               object
dropout_risk            float64
dtype: object

In [13]:
df.index

RangeIndex(start=0, stop=1000000, step=1)

In [14]:
df.columns

Index(['age', 'gender', 'academic_year', 'study_hours_per_day',
       'exam_pressure', 'academic_performance', 'stress_level',
       'anxiety_score', 'depression_score', 'sleep_hours', 'physical_activity',
       'social_support', 'screen_time', 'internet_usage', 'financial_stress',
       'family_expectation', 'burnout_score', 'mental_health_index',
       'risk_level', 'dropout_risk'],
      dtype='object')

In [15]:
df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,4.404825,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,2.664749,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,4.219224,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,3.634823,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,5.501813,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000

OBERSEVE THE NUMBER OF STUDENTS IN EACH CATEGORY

In [16]:
df['gender'].value_counts()

gender
Female    480070
Male      479643
Other      40287
Name: count, dtype: int64

CORRELATION OF EACH AND EVERY COLUMN WITH EVERY COLUMN

In [17]:
df.corr(numeric_only= True)

,age,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,dropout_risk
age,1.000000,0.000043,-0.000610,-0.000484,0.000720,-0.000772,-0.000244,-0.001668,-0.001298,-0.000132,-0.000351,0.000647,0.001083,-0.001369,-0.001219,-0.001016,0.000946,-0.001895
academic_year,0.000043,1.000000,0.000817,0.000236,0.000567,0.001190,0.001105,0.001218,-0.001716,-0.000965,0.000839,0.001153,0.001252,-0.000758,-0.000850,0.000555,-0.001332,-0.001220
study_hours_per_day,-0.000610,0.000817,1.000000,0.766089,0.388611,0.353023,0.269162,0.218664,-0.003293,0.000340,0.000561,-0.000747,-0.001658,0.000583,0.001022,0.335132,-0.335030,0.187382
exam_pressure,-0.000484,0.000236,0.766089,1.000000,0.126926,0.458992,0.350407,0.284634,-0.001802,0.000230,0.000802,-0.000021,-0.000916,0.000483,0.000788,0.434376,-0.435846,0.243437
academic_performance,0.000720,0.000567,0.388611,0.126926,1.000000,0.059694,0.045428,0.035889,-0.001585,-0.000841,0.000202,-0.001054,-0.001149,-0.000148,-0.000577,0.057089,-0.056318,0.032104
stress_level,-0.000772,0.001190,0.353023,0.458992,0.059694,1.000000,0.760930,0.622581,-0.263445,-0.174044,-0.000304,-0.001230,-0.001952,0.467430,0.347338,0.753111,-0.949393,0.554140
anxiety_score,-0.000244,0.001105,0.269162,0.350407,0.045428,0.760930,1.000000,0.476458,-0.200482,-0.131930,-0.000551,-0.001243,-0.001520,0.353918,0.263811,0.668450,-0.868666,0.461764
depression_score,-0.001668,0.001218,0.218664,0.284634,0.035889,0.622581,0.476458,1.000000,-0.165048,-0.109557,-0.364971,0.000012,-0.000297,0.291849,0.214574,0.642612,-0.763197,0.654336
sleep_hours,-0.001298,-0.001716,-0.003293,-0.001802,-0.001585,-0.263445,-0.200482,-0.165048,1.000000,-0.000144,0.000076,-0.000441,-0.000980,0.000055,-0.000140,-0.371386,0.250408,-0.191171
physical_activity,-0.000132,-0.000965,0.000340,0.000230,-0.000841,-0.174044,-0.131930,-0.109557,-0.000144,1.000000,0.001670,0.001694,0.001188,-0.000501,0.000919,-0.110074,0.165397,-0.070918
social_support,-0.000351,0.000839,0.000561,0.000802,0.000202,-0.000304,-0.000551,-0.364971,0.000076,0.001670,1.000000,-0.001604,-0.001114,-0.000137,-0.001387,-0.229811,0.102367,-0.394994
screen_time,0.000647,0.001153,-0.000747,-0.000021,-0.001054,-0.001230,-0.001243,0.000012,-0.000441,0.001694,-0.001604,1.000000,0.891185,-0.002447,-0.000205,-0.001215,0.001057,-0.000959
internet_usage,0.001083,0.001252,-0.001658,-0.000916,-0.001149,-0.001952,-0.001520,-0.000297,-0.000980,0.001188,-0.001114,0.891185,1.000000,-0.001788,-0.000454,-0.001151,0.001608,-0.001100
financial_stress,-0.001369,-0.000758,0.000583,0.000483,-0.000148,0.467430,0.353918,0.291849,0.000055,-0.000501,-0.000137,-0.002447,-0.001788,1.000000,-0.001073,0.295702,-0.443399,0.406470
family_expectation,-0.001219,-0.000850,0.001022,0.000788,-0.000577,0.347338,0.263811,0.214574,-0.000140,0.000919,-0.001387,-0.000205,-0.000454,-0.001073,1.000000,0.217843,-0.329124,0.138195
burnout_score,-0.001016,0.000555,0.335132,0.434376,0.057089,0.753111,0.668450,0.642612,-0.371386,-0.110074,-0.229811,-0.001215,-0.001151,0.295702,0.217843,1.000000,-0.796527,0.689748
mental_health_index,0.000946,-0.001332,-0.335030,-0.435846,-0.056318,-0.949393,-0.868666,-0.763197,0.250408,0.165397,0.102367,0.001057,0.001608,-0.443399,-0.329124,-0.796527,1.000000,-0.626425
dropout_risk,-0.001895,-0.001220,0.187382,0.243437,0.032104,0.554140,0.461764,0.654336,-0.191171,-0.070918,-0.394994,-0.000959,-0.001100,0.406470,0.138195,0.689748,-0.626425,1.000000

CHECK THE CORRELATION OF THE ACADEMIC YEAR WITH BURNOUT SCORE

In [18]:
df['academic_year'].corr(df['burnout_score'])

np.float64(0.0005549934288189812)

CHECK THE CORRELATION OF THE FINANCAIL STRESS WITH BURNOUT SCORE

In [19]:
df['financial_stress'].corr(df['burnout_score'])

np.float64(0.2957017270225939)

CHECK MANY NUMBER OF STUDENT IN EACH AGE

In [20]:
df['age'].value_counts()

age
21    77169
29    77157
19    77141
20    77057
17    76996
22    76938
23    76937
26    76927
18    76927
28    76783
25    76708
24    76672
27    76588
Name: count, dtype: int64

GROUP BY AGGREGATION OF AGE

In [21]:
extract = df.groupby('age')['age'].agg(['max','min','mean','count','median'])
extract

     max  min  mean  count  median
age
17    17   17  17.0  76996    17.0
18    18   18  18.0  76927    18.0
19    19   19  19.0  77141    19.0
20    20   20  20.0  77057    20.0
21    21   21  21.0  77169    21.0
22    22   22  22.0  76938    22.0
23    23   23  23.0  76937    23.0
24    24   24  24.0  76672    24.0
25    25   25  25.0  76708    25.0
26    26   26  26.0  76927    26.0
27    27   27  27.0  76588    27.0
28    28   28  28.0  76783    28.0
29    29   29  29.0  77157    29.0

MAXIMUM VALUES FROM EACH AND COLUMNS

In [22]:
maximums = extract.max()
maximums

max          29.0
min          29.0
mean         29.0
count     77169.0
median       29.0
dtype: float64

HOW MANY YEAR WE HAVE IN TOTAL

In [23]:
df['academic_year'].value_counts().sort_index(ascending=True)

academic_year
1    249671
2    249886
3    250433
4    250010
Name: count, dtype: int64

In [24]:
df.columns

Index(['age', 'gender', 'academic_year', 'study_hours_per_day',
       'exam_pressure', 'academic_performance', 'stress_level',
       'anxiety_score', 'depression_score', 'sleep_hours', 'physical_activity',
       'social_support', 'screen_time', 'internet_usage', 'financial_stress',
       'family_expectation', 'burnout_score', 'mental_health_index',
       'risk_level', 'dropout_risk'],
      dtype='object')

In [25]:
df.pivot_table(values=['stress_level','anxiety_score','burnout_score', 'depression_score', 'sleep_hours', 'physical_activity',
       'social_support', 'screen_time', 'internet_usage', 'financial_stress'],
              index= 'academic_year',aggfunc= 'median')

,anxiety_score,burnout_score,depression_score,financial_stress,internet_usage,physical_activity,screen_time,sleep_hours,social_support,stress_level
academic_year,,,,,,,,,,
1,2.966530,1.495761,1.048217,5.002243,5.001952,3.003686,5.000450,6.505697,4.990006,4.243645
2,2.968858,1.494900,1.044697,4.994456,4.990776,3.000103,4.993638,6.503896,5.007015,4.241081
3,2.973817,1.501089,1.050269,5.007132,5.008849,3.001405,5.009858,6.501466,4.998646,4.246564
4,2.968396,1.494167,1.047814,5.001611,5.005139,2.996764,5.010098,6.496986,5.000590,4.244394

(anxiety_score burnout_score depression_score financial_stress internet_usage physical_activity screen_time sleep_hours social_support stress_level) ACCORDING TO EACH AND EVEY ADCADEMIC YEAR

In [26]:
bins = [16,21,26,30]
lables = ['16-20','21-25','26-30'] 
df['age_group'] = pd.cut(df['age'],bins=bins,labels=lables)
df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,...,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk,age_group
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,...,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601,21-25
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,...,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000,16-20
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,...,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941,26-30
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,...,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592,26-30
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,...,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000,21-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,...,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000,21-25
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,...,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000,16-20
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,...,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209,21-25
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,...,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401,26-30
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,...,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000,16-20

SHOWS FREQUENCY COUNT OF COMBINATION OF ACADEMIC YEAR AND AGE GROUP

In [27]:
pd.crosstab(df['academic_year'],df['age_group'])

age_group      16-20  21-25  26-30
academic_year
1              96040  96351  57280
2              96392  96096  57398
3              96266  95992  58175
4              96592  95743  57675

In [28]:
df.pivot_table(values=['stress_level', 'anxiety_score', 
                        'depression_score', 'burnout_score'],
              index= 'academic_performance',aggfunc='mean')

,anxiety_score,burnout_score,depression_score,stress_level
academic_performance,,,,
42.365714,3.410781,1.286077,0.000000,5.119938
44.583131,4.417189,2.622218,1.138807,6.115943
45.140993,2.482022,1.282179,2.436040,5.012641
45.172144,2.570863,0.179506,0.388041,4.298136
46.011942,2.615363,0.000000,1.484275,2.293314
...,...,...,...,...
96.143636,0.000000,0.003031,0.146553,2.428828
96.494698,3.003909,0.000000,0.031877,4.796645
96.710590,1.776386,1.690305,1.023271,3.316419
96.759436,5.486652,3.689253,2.271919,6.754956
97.246309,3.768015,3.827637,2.493243,5.391740

In [29]:
df['academic_performance']

0         68.411114
1         67.682159
2         58.372363
3         68.925653
4         69.141915
            ...
999995    79.292283
999996    70.718819
999997    79.121184
999998    69.424255
999999    58.666123
Name: academic_performance, Length: 1000000, dtype: float64

In [30]:
print(df['academic_performance'].min())
df['academic_performance'].max()

42.36571413222889

97.2463088953687

In [31]:
x = df['academic_performance']
def performance(x):
    if x>40 and x<=50:
        return 'Low'
    elif x>=51 and x<=70:
        return 'Medium'
    elif x>=71 and x<=90:
        return 'High'
    elif x>=91 and x<100:
        return 'Above 90'

df['performance_category'] = df['academic_performance'].apply(performance)

In [32]:
df['performance_category'].value_counts().sort_index(ascending=False)

performance_category
Medium      429508
Low             96
High        499565
Above 90       215
Name: count, dtype: int64

In [33]:
df['academic_performance'].corr(df['mental_health_index'])

np.float64(-0.05631829340527141)

In [34]:
df.columns

Index(['age', 'gender', 'academic_year', 'study_hours_per_day',
       'exam_pressure', 'academic_performance', 'stress_level',
       'anxiety_score', 'depression_score', 'sleep_hours', 'physical_activity',
       'social_support', 'screen_time', 'internet_usage', 'financial_stress',
       'family_expectation', 'burnout_score', 'mental_health_index',
       'risk_level', 'dropout_risk', 'age_group', 'performance_category'],
      dtype='object')

In [35]:
df.groupby('academic_year')['stress_level'].mean()

academic_year
1    4.243164
2    4.245142
3    4.250043
4    4.247488
Name: stress_level, dtype: float64

In [36]:
df.groupby('age_group')['anxiety_score'].max()

C:\Users\Kirti Gupta\AppData\Local\Temp\ipykernel_32428\1653296077.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_group')['anxiety_score'].max()

age_group
16-20     9.625411
21-25    10.000000
26-30     9.698745
Name: anxiety_score, dtype: float64

THese AGE GROUP HAVE MAXIMUM ANXIETY SCORE

In [37]:
df['financial_stress'].corr(df['depression_score'])

np.float64(0.2918491481076545)

it shows the correlation between financial stress and dipression score and as the result in positive so there is positive relation which means as the financial stress increases the dipression score is also increases.....

In [38]:
low_sleep = df[df['sleep_hours']<6]
low_sleep['burnout_score'].mean()

np.float64(2.443096352519892)

it show an average of burnout score of those student who sleep less than 6 hours

In [39]:
df['sleep_hours'].cov(df['academic_performance'])

np.float64(-0.013211289355217148)

No consistent linear relationship (sleep and performance move independently).

In [40]:
df[df['risk_level'] == 'High']

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,...,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk,age_group,performance_category
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,...,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592,26-30,Medium
67,28,Female,1,7.238666,6.651910,81.511528,7.027182,7.096204,1.283728,3.000000,...,1.119998,1.000000,2.905979,6.491582,7.300219,4.675148,High,5.286210,26-30,High
109,25,Female,3,5.835099,6.337624,75.595578,7.358378,5.043839,2.637582,3.000000,...,6.453643,6.594301,5.224008,7.854964,6.578352,4.752223,High,4.591307,21-25,High
139,24,Female,3,8.758381,7.252902,82.848484,7.696048,5.517964,4.516454,5.719817,...,6.647169,5.753171,6.428922,5.970836,6.632176,3.911256,High,3.768555,21-25,High
257,27,Male,4,4.230159,5.320746,69.952137,7.787992,6.148513,1.777914,3.000000,...,3.707136,3.438583,7.386514,8.743052,6.182135,4.506875,High,1.045115,26-30,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999770,22,Male,1,8.213205,8.840251,63.498898,5.336072,6.156893,1.672817,6.652082,...,2.813152,2.785243,6.024032,5.088323,6.456043,5.516658,High,3.715244,21-25,Medium
999824,19,Female,2,7.751245,8.619756,72.544590,6.821064,4.979357,2.451883,4.645891,...,6.498858,6.226121,8.883055,5.374659,6.851131,5.042202,High,6.005474,16-20,High
999950,19,Female,1,8.822492,7.898290,73.841843,7.336570,4.866981,3.834999,4.553183,...,7.923821,9.157752,3.323457,9.123560,6.451744,4.454778,High,4.883053,16-20,High
999962,25,Male,3,6.468861,7.437165,74.762017,8.564163,5.415466,4.994528,3.639381,...,4.377999,5.438555,6.490269,8.096803,7.800679,3.451337,High,3.924598,21-25,High
999990,25,Male,1,8.192357,9.956581,71.684562,7.727386,6.379695,2.692690,4.323611,...,4.914095,3.915136,6.145899,6.410987,7.467518,4.187330,High,3.428087,21-25,High

In [41]:
df['family_expectation'].corr(df['dropout_risk'])

np.float64(0.1381949023964737)

In [42]:
df.groupby('family_expectation')['dropout_risk'].mean()

family_expectation
0.000000     0.801061
0.000663     0.910394
0.002302     0.336383
0.002771     0.302191
0.003690     4.185137
               ...
9.999909     2.800451
9.999935     3.129505
9.999971     1.660043
9.999996     3.253827
10.000000    1.751452
Name: dropout_risk, Length: 975615, dtype: float64

**PERFORMING A HYPOTHESIS TESTING**

In [43]:
from scipy.stats import stats

**SAMPLE DATA**

In [44]:
sample_df = df.loc[0:100,:]
sample_df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,...,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk,age_group,performance_category
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,...,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601,21-25,Medium
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,...,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000,16-20,Medium
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,...,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941,26-30,Medium
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,...,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592,26-30,Medium
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,...,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000,21-25,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,18,Female,3,7.958061,9.502525,75.987530,6.433656,3.728825,1.373351,8.517508,...,5.133156,4.177367,5.851558,8.886635,2.670052,5.895885,Low,3.365640,16-20,High
97,21,Female,4,8.706658,7.597969,77.639096,7.092993,5.946303,3.397777,5.425566,...,4.937139,6.214089,5.486136,8.515191,3.597517,4.359579,Medium,1.732625,16-20,High
98,24,Female,4,6.371529,5.788810,71.993119,4.895763,4.286411,1.329208,4.521030,...,4.227321,4.804397,3.157183,9.168905,2.384478,6.357009,Low,0.020018,21-25,High
99,26,Male,2,5.181145,6.049036,69.576456,4.206685,2.240030,1.564546,6.080874,...,4.964267,4.423308,3.422289,7.234659,1.864900,7.175953,Low,2.337574,21-25,Medium
100,25,Female,4,4.163109,5.813996,70.262178,3.252558,2.056689,1.618274,8.412492,...,6.151900,5.423495,1.751135,7.676444,1.901485,7.596488,Low,2.556583,21-25,None

Question: Is there a significant difference in depression_score between male and female students?

**PERFORMING T-TEST [TWO SAMPLE T-TEST]**

According to the formula of the t-test we want:
i. sample mean 
ii. sample size 
iii. population mean 
iv. population std

In [45]:
sample_df.dtypes

age                        int64
gender                    object
academic_year              int64
study_hours_per_day      float64
exam_pressure            float64
academic_performance     float64
stress_level             float64
anxiety_score            float64
depression_score         float64
sleep_hours              float64
physical_activity        float64
social_support           float64
screen_time              float64
internet_usage           float64
financial_stress         float64
family_expectation       float64
burnout_score            float64
mental_health_index      float64
risk_level                object
dropout_risk             float64
age_group               category
performance_category      object
dtype: object

we have to extract the males student and there corresponing dipression score and same goes with female students

In [46]:
male_group = sample_df[sample_df['gender']=='Male']['depression_score']
male_group

0     1.986730
1     0.000000
2     0.851996
3     4.285645
4     0.000000
8     2.034520
10    3.154455
11    1.512020
13    2.604256
15    5.443044
16    3.341060
20    0.000000
21    0.000000
24    0.550068
25    0.000000
28    1.554067
29    1.001023
32    2.520377
35    0.000000
38    2.061004
39    0.000000
40    0.000000
41    0.177563
44    2.459315
47    0.823850
48    0.731195
50    0.189186
51    2.408131
52    0.000000
55    1.822995
57    3.503298
60    0.000000
61    1.297821
63    1.301950
65    0.824686
66    2.132065
72    1.026106
73    0.263609
74    0.572797
79    3.942605
80    0.000000
82    0.000000
85    2.140893
87    0.000000
88    2.761906
91    1.468604
93    4.160522
94    0.000000
99    1.564546
Name: depression_score, dtype: float64

In [47]:
female_group = sample_df[sample_df['gender']=='Female']['depression_score']
female_group

5      2.313338
6      0.000000
7      0.782428
9      1.127562
12     1.551500
14     0.000000
17     0.941373
18     0.000000
19     2.685580
22     0.368617
23     2.390093
26     0.000000
27     0.000000
30     1.268035
31     0.000000
33     2.124780
34     1.658326
36     0.000000
37     1.044467
42     1.015528
43     0.734991
45     0.000000
46     2.374937
53     1.309679
54     3.091147
56     2.156019
58     2.292689
59     0.000000
62     0.048319
64     3.451744
67     1.283728
68     4.950093
69     0.000000
70     3.065559
71     0.312963
75     0.000000
76     2.471688
77     3.121287
78     0.000000
81     1.059989
83     1.260878
84     1.746261
86     2.577462
89     0.938148
90     0.153437
92     1.516138
95     3.533563
96     1.373351
97     3.397777
98     1.329208
100    1.618274
Name: depression_score, dtype: float64

In [48]:
m_mean = male_group.mean()
std_m = male_group.std()
n_m = len(male_group)
print(f"Male: mean={m_mean:.2f}, std={std_m:.2f}, n={n_m}")

Male: mean=1.40, std=1.40, n=49

In [49]:
f_mean = female_group.mean()
std_f = female_group.std()
n_f = len(female_group)
print(f"Female: mean={f_mean:.2f}, std={std_f:.2f}, n={n_f}")

Female: mean=1.38, std=1.22, n=51

**APPLING THE FORMULA (manual method)**


STEP 1 : SPECIFY THE H₀ i.e.. "there is no difference in dipression score of male and female.... "
STEP 2 : SPECIFY THE H₁ i.e.. "there is a difference in dipression score of male and female.... "
STEP 3 : SET THE SIGNIFICANCE LEVEL i.e.. "generally is take as 0.05 or 5%"
STEP 4 : CALCULATE THE TEST STATISTICS ANN THE CORRESPONDING P-VALUE.....
STEP 5 : DRAWING CONCLUSION

STEP 1 :NULL HYPOTHESIS ----> "there is no difference in dipression score of male and female.... "
STEP 2 :ALTERNATE HYPOTHESIS ----> "there is a difference in dipression score of male and female....

STEP 3 : have Calculate t-statisticz

In [50]:
t_stat = (m_mean - f_mean) / np.sqrt((std_m**2 / n_m) + (std_f**2 / n_f))
t_stat

np.float64(0.0617899392217308)

STEP 4 : Calculate degrees of freedom (Welch–Satterthwaite formula) , Calculate p-value (two-tailed)

In [51]:
df = ( (std_m**2/n_m + std_f**2/n_f)**2 ) / ( (std_m**2/n_m)**2/(n_m-1) +
        (std_f**2/n_f)**2/(n_f-1) )
df

94.93575141697372

In [52]:
from scipy.stats import t

In [53]:
p_value = 2 * (1 - t.cdf(abs(t_stat), df))
p_value

np.float64(0.9508600166044028)

**STEP 4 : DRAWING CONCLUSION**

In [54]:
alpha = 0.05

In [55]:
if p_value< alpha:
    print("Rejecting the H₀.")
else:
    print("Fail to reject H₀.")

Fail to reject H₀.

as we can see that there p_values>0.05 from this we can derived that we have are failing to reject H₀ which means we accepting the null hypthesis i.e.. ", NO DIFFERENCE , NO RELATION , NO EFFECT between the dipression_score of male and female students"

 **DIRECT METHOD(using ttest_ind)**

Gives you both t-statistic and p-value directly.
No need to calculate anything manually.

In [56]:
from scipy.stats import ttest_ind

In [57]:
t_stat, p_value = ttest_ind(male_group, female_group)
print(f"t = {t_stat:.5f},p-value = {p_value:.5f}")

t = 0.06196,p-value = 0.95072

In [58]:
alpha = 0.05
if p_value< alpha:
    print("Rejecting the H₀.")
else:
    print("Fail to reject H₀.")

Fail to reject H₀.