In [1]:
import numpy as np 
import pandas as pd 
import matplotlib as plt 
import seaborn as sns

In [9]:
df = pd.read_csv(r"C:\Users\Kirti Gupta\Desktop\MG'S LEARNING\student_mental_health_burnout_1M.csv")
df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,22,Female,3,5.784771,4.922653,79.292283,2.033221,1.238058,0.000000,8.214062,4.404825,9.013047,1.000000,1.664220,5.374860,4.875184,0.000000,8.815294,Low,0.000000
999996,20,Male,1,3.795347,4.706976,70.718819,4.144918,2.768193,1.405596,6.701671,2.664749,8.678769,2.641657,2.923180,5.100452,5.495558,1.166516,7.089896,Low,0.000000
999997,24,Female,3,8.814898,8.750319,79.121184,4.715533,4.138000,1.931592,6.569535,4.219224,4.881412,5.224459,3.855320,2.290888,6.792472,1.997088,6.292909,Low,1.172209
999998,29,Female,4,5.920859,6.678223,69.424255,5.553155,5.681447,1.366879,8.017232,3.634823,5.232852,2.668379,2.951508,5.885972,6.829679,2.731137,5.664240,Low,1.968401
999999,17,Female,2,5.733588,6.061671,58.666123,2.936770,2.533496,0.661940,6.868650,5.501813,2.832691,1.000000,1.000000,5.187394,5.162718,1.342995,7.866661,Low,0.000000

**VISUALIZING IN THE SAMPLE DATA**

In [10]:
sample_df = df.loc[0:100,:]
sample_df

,age,gender,academic_year,study_hours_per_day,exam_pressure,academic_performance,stress_level,anxiety_score,depression_score,sleep_hours,physical_activity,social_support,screen_time,internet_usage,financial_stress,family_expectation,burnout_score,mental_health_index,risk_level,dropout_risk
0,23,Male,2,5.596071,6.487218,68.411114,4.116950,2.275713,1.986730,6.880545,2.728861,6.470080,4.993801,4.983157,3.446626,3.586147,2.037344,7.074487,Low,1.746601
1,20,Male,3,5.597171,5.631481,67.682159,0.349489,0.000000,0.000000,7.463339,3.690866,0.000000,3.862980,5.136124,2.814039,5.478666,0.000000,9.860204,Low,0.000000
2,29,Male,2,2.580491,6.015297,58.372363,3.476177,2.425201,0.851996,8.946670,3.296720,6.901725,5.428880,3.058333,4.918515,6.068155,0.000000,7.626370,Low,0.696941
3,27,Male,4,4.607208,6.684005,68.925653,6.778843,4.512425,4.285645,4.571380,2.065480,2.349857,6.304842,6.931147,6.915885,6.557540,7.227651,4.649042,High,5.380592
4,24,Male,4,2.186569,4.010945,69.141915,1.854595,1.102558,0.000000,5.989324,4.026504,4.512921,4.903146,5.134903,4.382820,5.934779,0.000000,8.927394,Low,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,18,Female,3,7.958061,9.502525,75.987530,6.433656,3.728825,1.373351,8.517508,2.637354,6.348850,5.133156,4.177367,5.851558,8.886635,2.670052,5.895885,Low,3.365640
97,21,Female,4,8.706658,7.597969,77.639096,7.092993,5.946303,3.397777,5.425566,2.366063,4.963052,4.937139,6.214089,5.486136,8.515191,3.597517,4.359579,Medium,1.732625
98,24,Female,4,6.371529,5.788810,71.993119,4.895763,4.286411,1.329208,4.521030,3.077423,6.007947,4.227321,4.804397,3.157183,9.168905,2.384478,6.357009,Low,0.020018
99,26,Male,2,5.181145,6.049036,69.576456,4.206685,2.240030,1.564546,6.080874,1.241435,3.757818,4.964267,4.423308,3.422289,7.234659,1.864900,7.175953,Low,2.337574
100,25,Female,4,4.163109,5.813996,70.262178,3.252558,2.056689,1.618274,8.412492,5.056176,3.194666,6.151900,5.423495,1.751135,7.676444,1.901485,7.596488,Low,2.556583